# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RubiApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for RubiApp
  pod 'SVProgressHUD'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'ReactorKit', '~> 2.0.1'
  pod 'SWXMLHash', '~> 4.9.0'
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'PinLayout', '~> 1.8.9'
end
